# Header

menu:
  主页: /
  # 分享: /tags/随笔/

# SubNav
subnav:
  # github: "https://github.com/myxiaoshen/"
  rss: "https://pan.xlmy.net"
  # zhihu: "#"
  # qq: "https://qm.qq.com/cgi-bin/qm/qr?k=Zg3m93U7KAzHABWMsWc39vWsLYD6O-Co&jump_from=webapi"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  # segmentfault: ""
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:wenchadanjiu@protonmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  # linkedin: ""

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字more
excerpt_link:  阅读全文
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: false
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: '9566ddbecb4780f4ab3d0656ab315155'
google_analytics: ''
favicon: /img/my.png

#你的头像url
avatar: /img/my.png


#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true





# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  # friends: '友链'
  aboutme: '关于我'

# friends:
#   友情链接1: http://localhost:4000/

aboutme: <br>俺是一个小学生业余喜欢在网上跟着做一些有趣的事情和diy一些电子设备，看看高效率的技术什么的。也喜欢去网上copy一些好玩实用的东西记录下来，主要是方便自己以后需要这些的时候回顾一下。<br>最近在专研python自动化和一些常用的算法。<br>我是一个比较开朗的，心细，写代码也爱写备注的娃娃。<br> 不擅长与女娃娃交际。看着妹子就脸红 -_-|     <br>业余时间用hexo捣了一个博客，希望这些玩意能够在工作中帮到大家（文章中错别字可能有很多233- -\|）。

